services:
  db:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: ${POSTGRES_NAME}
    volumes:
      - db-data:/data/postgres
    ports:
      - "5332:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_NAME}" ]
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  db-data:
